# Site settings
author: Alex Marusin
title: Time to Pretend
header-img: img/home-bg.png
email: amarusin18@gmail.com
copyright_name: Alex Marusin
description: > # this means to ignore newlines until "baseurl:"
  A novice programmers journey through the ether
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ajmar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
